project_dir: "dbt"
profiles_dir: "dbt"
state: "dbt/reference_manifest.json"
runner: "docker"

docker:
  image: "my-registry/dbt:latest"
  volumes:
    - "dbt:/path-in-your-container:rw"
    - "${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}:ro"
  env:
    - "DBT_PROFILES_DIR=/dbt"
    - "USER=${USER}"
    - "DBT_STATE=${DBT_STATE}"
