DBT_PROJECT_DIR: "dbt"
DBT_PROFILES_DIR: "dbt"
DBT_DOCKER_IMAGE: "my-registry/dbt:latest"
DBT_STATE: "dbt/reference_manifest.json"
DBT_RUNNER: "docker"
DBT_DOCKER_VOLUMES:
  - "dbt:/path-in-your-container:rw"
  - "${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}:ro"
DBT_DOCKER_ENV: 
  - "DBT_PROFILES_DIR=/dbt"
  - "USER=${USER}"
  - "GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}"
  - "DBT_STATE=${DBT_STATE}"