name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  
  pypi:
    needs: tests
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/publish-pypi.yml
    secrets: inherit